<?php

namespace Unity\Domain\Proxy\__CG__\Unity\Domain\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \Unity\Domain\Model\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDescription($desc)
    {
        $this->__load();
        return parent::setDescription($desc);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setUserId($id)
    {
        $this->__load();
        return parent::setUserId($id);
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function getBackLog()
    {
        $this->__load();
        return parent::getBackLog();
    }

    public function addStory(\Unity\Domain\Model\Story $story)
    {
        $this->__load();
        return parent::addStory($story);
    }

    public function stories()
    {
        $this->__load();
        return parent::stories();
    }

    public function getStory($storyId)
    {
        $this->__load();
        return parent::getStory($storyId);
    }

    public function deleteStory(\Unity\Domain\Model\Story $story)
    {
        $this->__load();
        return parent::deleteStory($story);
    }

    public function user()
    {
        $this->__load();
        return parent::user();
    }

    public function setUser(\Unity\Domain\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function team()
    {
        $this->__load();
        return parent::team();
    }

    public function backlog()
    {
        $this->__load();
        return parent::backlog();
    }

    public function unassignedStoriesBacklog()
    {
        $this->__load();
        return parent::unassignedStoriesBacklog();
    }

    public function releasePlannedBacklog()
    {
        $this->__load();
        return parent::releasePlannedBacklog();
    }

    public function sprintUnplannedBacklog()
    {
        $this->__load();
        return parent::sprintUnplannedBacklog();
    }

    public function sprintPlannedBacklog()
    {
        $this->__load();
        return parent::sprintPlannedBacklog();
    }

    public function releases()
    {
        $this->__load();
        return parent::releases();
    }

    public function isOverlapping(\Unity\Domain\Model\Release $existing)
    {
        $this->__load();
        return parent::isOverlapping($existing);
    }

    public function addRelease(\Unity\Domain\Model\Release $toAdd)
    {
        $this->__load();
        return parent::addRelease($toAdd);
    }

    public function removeRelease(\Unity\Domain\Model\Release $release)
    {
        $this->__load();
        return parent::removeRelease($release);
    }

    public function averageVelocity()
    {
        $this->__load();
        return parent::averageVelocity();
    }

    public function currentRelease()
    {
        $this->__load();
        return parent::currentRelease();
    }

    public function currentSprint()
    {
        $this->__load();
        return parent::currentSprint();
    }

    public function release($releaseId)
    {
        $this->__load();
        return parent::release($releaseId);
    }

    public function storyStatuses()
    {
        $this->__load();
        return parent::storyStatuses();
    }

    public function addStoryStatus(\Unity\Domain\Model\StoryStatus $status)
    {
        $this->__load();
        return parent::addStoryStatus($status);
    }

    public function storyStatus($status)
    {
        $this->__load();
        return parent::storyStatus($status);
    }

    public function removeStoryStatus($status)
    {
        $this->__load();
        return parent::removeStoryStatus($status);
    }

    public function hasStoryStatus($status)
    {
        $this->__load();
        return parent::hasStoryStatus($status);
    }

    public function orderStoryStatuses(array $order)
    {
        $this->__load();
        return parent::orderStoryStatuses($order);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'description', 'userId', 'stories', 'releases', 'user', 'members', 'storyStatuses');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}