<?php

namespace Unity\Domain\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UnityDomainModelReleaseProxy extends \Unity\Domain\Model\Release implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->_load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->_load();
        return parent::getTitle();
    }

    public function setDescription($desc)
    {
        $this->_load();
        return parent::setDescription($desc);
    }

    public function getDescription()
    {
        $this->_load();
        return parent::getDescription();
    }

    public function setStartDate(\DateTime $date)
    {
        $this->_load();
        return parent::setStartDate($date);
    }

    public function getStartDate()
    {
        $this->_load();
        return parent::getStartDate();
    }

    public function setEndDate(\DateTime $date)
    {
        $this->_load();
        return parent::setEndDate($date);
    }

    public function getEndDate()
    {
        $this->_load();
        return parent::getEndDate();
    }

    public function getDueDate()
    {
        $this->_load();
        return parent::getDueDate();
    }

    public function setDueDate(\DateTime $dueDate)
    {
        $this->_load();
        return parent::setDueDate($dueDate);
    }

    public function getBackLog()
    {
        $this->_load();
        return parent::getBackLog();
    }

    public function setProduct(\Unity\Domain\Model\Product $product = NULL)
    {
        $this->_load();
        return parent::setProduct($product);
    }

    public function product()
    {
        $this->_load();
        return parent::product();
    }

    public function backlog()
    {
        $this->_load();
        return parent::backlog();
    }

    public function addStory(\Unity\Domain\Model\Story $story)
    {
        $this->_load();
        return parent::addStory($story);
    }

    public function removeStory(\Unity\Domain\Model\Story $story)
    {
        $this->_load();
        return parent::removeStory($story);
    }

    public function asSprints(\Doctrine\Common\Collections\Collection $stories, $velocity)
    {
        $this->_load();
        return parent::asSprints($stories, $velocity);
    }

    public function addSprint(\Unity\Domain\Model\Sprint $sprint)
    {
        $this->_load();
        return parent::addSprint($sprint);
    }

    public function sprints()
    {
        $this->_load();
        return parent::sprints();
    }

    public function unplannedBacklog()
    {
        $this->_load();
        return parent::unplannedBacklog();
    }

    public function plannedBacklog()
    {
        $this->_load();
        return parent::plannedBacklog();
    }

    public function epicBacklog()
    {
        $this->_load();
        return parent::epicBacklog();
    }

    public function sprint($sprintId)
    {
        $this->_load();
        return parent::sprint($sprintId);
    }

    public function removeSprint(\Unity\Domain\Model\Sprint $sprint)
    {
        $this->_load();
        return parent::removeSprint($sprint);
    }

    public function sprintThrough(\DateTime $date)
    {
        $this->_load();
        return parent::sprintThrough($date);
    }

    public function clearBacklog()
    {
        $this->_load();
        return parent::clearBacklog();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'description', 'startDate', 'endDate', 'dueDate', 'product', 'stories', 'sprints');
    }
}