<?php

namespace Unity\Domain\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UnityDomainModelUserProxy extends \Unity\Domain\Model\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getEmail()
    {
        $this->_load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->_load();
        return parent::setEmail($email);
    }

    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function products()
    {
        $this->_load();
        return parent::products();
    }

    public function addProduct(\Unity\Domain\Model\Product $product)
    {
        $this->_load();
        return parent::addProduct($product);
    }

    public function removeProduct(\Unity\Domain\Model\Product $product)
    {
        $this->_load();
        return parent::removeProduct($product);
    }

    public function getFirstName()
    {
        $this->_load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->_load();
        return parent::setFirstName($firstName);
    }

    public function getLastName()
    {
        $this->_load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->_load();
        return parent::setLastName($lastName);
    }

    public function getTelephone()
    {
        $this->_load();
        return parent::getTelephone();
    }

    public function setTelephone($telephone)
    {
        $this->_load();
        return parent::setTelephone($telephone);
    }

    public function getAddress()
    {
        $this->_load();
        return parent::getAddress();
    }

    public function setAddress($address)
    {
        $this->_load();
        return parent::setAddress($address);
    }

    public function getCountry()
    {
        $this->_load();
        return parent::getCountry();
    }

    public function setCountry($country)
    {
        $this->_load();
        return parent::setCountry($country);
    }

    public function getPostcode()
    {
        $this->_load();
        return parent::getPostcode();
    }

    public function setPostcode($postcode)
    {
        $this->_load();
        return parent::setPostcode($postcode);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'email', 'password', 'telephone', 'address', 'country', 'postcode', 'products', 'firstName', 'lastName');
    }
}