<?php

namespace Unity\Domain\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UnityDomainModelSprintProxy extends \Unity\Domain\Model\Sprint implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setStories(\Doctrine\Common\Collections\Collection $stories)
    {
        $this->_load();
        return parent::setStories($stories);
    }

    public function backlog()
    {
        $this->_load();
        return parent::backlog();
    }

    public function setGoal($goal)
    {
        $this->_load();
        return parent::setGoal($goal);
    }

    public function getGoal()
    {
        $this->_load();
        return parent::getGoal();
    }

    public function setStartDate(\DateTime $date)
    {
        $this->_load();
        return parent::setStartDate($date);
    }

    public function getStartDate()
    {
        $this->_load();
        return parent::getStartDate();
    }

    public function setEndDate(\DateTime $date)
    {
        $this->_load();
        return parent::setEndDate($date);
    }

    public function getEndDate()
    {
        $this->_load();
        return parent::getEndDate();
    }

    public function getStartsOn()
    {
        $this->_load();
        return parent::getStartsOn();
    }

    public function getEndsOn()
    {
        $this->_load();
        return parent::getEndsOn();
    }

    public function getVelocity()
    {
        $this->_load();
        return parent::getVelocity();
    }

    public function addStory(\Unity\Domain\Model\Story $story)
    {
        $this->_load();
        return parent::addStory($story);
    }

    public function removeStory(\Unity\Domain\Model\Story $story)
    {
        $this->_load();
        return parent::removeStory($story);
    }

    public function setRelease(\Unity\Domain\Model\Release $release = NULL)
    {
        $this->_load();
        return parent::setRelease($release);
    }

    public function release()
    {
        $this->_load();
        return parent::release();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'goal', 'startDate', 'endDate', 'stories', 'release');
    }
}