<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">

            <a class="brand" href="./index.html">WorkflowManager</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="dropdown">
                        <a href="#"
                           class="dropdown-toggle"
                           data-toggle="dropdown">
                            Account
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="">
                                <a href="./scaffolding.html">Scaffolding</a>
                            </li>
                            <li class="">
                                <a href="./base-css.html">Base CSS</a>
                            </li>
                        </ul>
                    </li>
                   
                    <li class="active">
                        <a href="./components.html">Components</a>
                    </li>
                    <li class="">
                        <a href="./javascript.html">Javascript plugins</a>
                    </li>
                    <li class="">
                        <a href="./less.html">Using LESS</a>
                    </li>
                    <li class="divider-vertical"></li>
                    <li class="">
                        <a href="./download.html">Customize</a>
                    </li>
                    <li class="">
                        <a href="./examples.html">Examples</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>