<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Workflow magic</title>
        <script data-main="js/main" src="js/libs/require/require.js"></script>
        <link href="/css/libs/jquery/jquery-ui.css"
              media="screen" rel="stylesheet" type="text/css"></link>
        <link href="/css/libs/bootstrap/bootstrap.min.css" media="screen"
              rel="stylesheet" type="text/css"></link> 

        <?= $this->headLink() ?>
        <?= $this->headScript() ?>

    </head>
    
    <body>
        <?= $this->layout()->content ?> 
    </body>
</html>