<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Sample backbone app</title>
        <script src="/jquery/js/jquery-1.5.1.min.js"></script>
        <script src="/jquery/js/jquery-ui-1.8.13.custom.min.js"></script>
        <script src="/jquery/js/jquery.form.js"></script>
        <script src="http://ajax.cdnjs.com/ajax/libs/underscore.js/1.1.4/underscore-min.js"></script>
        <script src="http://ajax.cdnjs.com/ajax/libs/backbone.js/0.3.3/backbone-min.js"></script>
        <script src="/app/app.js"></script>
        <link href="/jquery/css/redmond/jquery-ui-1.8.13.custom.css"
              media="screen" rel="stylesheet" type="text/css"></link>
        <link href="/bootstrap/bootstrap.min.css" media="screen"
              rel="stylesheet" type="text/css"></link> 
        <link href="/css/main.css" media="screen"
              rel="stylesheet" type="text/css"></link> 
        

        <?= $this->headLink() ?>
        <?= $this->headScript() ?>

    </head>

    <body>

        <?= $this->layout()->content ?> 
    </body>
</html>